version: "3.8"

services:
  postgres:
    container_name: wonder-postgres
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: user_qit
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: wonder
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
  springapp:
    container_name: wonder-springapp
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_DOMAIN: postgres
      DATABASE_PORT: 5432
      DATABASE_NAME: wonder
      DATABASE_USERNAME: user_qit
      DATABASE_PASSWORD: 123
    ports:
      - "8181:8181"
    depends_on:
      - postgres
