version: "3.8"

services:
  postgres:
    container_name: wonder-postgres
    image: postgres
    expose:
      - "5432"
    environment:
      POSTGRES_USER: k_app
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: wonder
    volumes:
      - ./dataset:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    restart: unless-stopped
  keycloak:
    image: jboss/keycloak
#    image: sleighzy/keycloak
    container_name: wonder-keycloak
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: wonder
      DB_USER: k_app
      DB_PASSWORD: 123
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin_password
    ports:
      - "8484:8080"
    depends_on:
      - postgres
    links:
      - "postgres:postgres"