application:
  title: Wonder
  version: 1.0.0
  keycloak-url: ${KEYCLOAK_URL:https://keycloak-3gn7q5gs6q-lm.a.run.app}
  realm: wonder
  client-id: wonder
  username: ${KEYCLOAK_ADMIN:k_app@mail.ru}
  password: ${KEYCLOAK_ADMIN_PASSWORD:k_pass5q}
  mode: ${APP_MODE:DEV}
  admin-keycloak-id: ${ADMIN_KEYCLOAK_ID:06f28b07-5d18-493a-9517-e1e7d78614a4}
  file-api:
    name: file-api
    url: ${FILE_API_URL:https://wonderfilemanagerepository-of5r5e4d7a-el.a.run.app}
  kaspi-api:
    url: ${KASPI_API_URL:https://kaspi.kz/shop/api/v2}
spring:
  codec:
    max-in-memory-size: 500KB
  datasource:
    url: ${DATABASE_URL}
    #    url: jdbc:postgresql://${DATABASE_DOMAIN:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:wonder}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER:${application.keycloak-url}/realms/${application.realm}}
          jwk-set-uri: ${OAUTH2_JWK:${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
server:
  servlet:
    context-path: '/api/'
  error:
    include-message: always
  port: ${PORT:8080}
  address: 0.0.0.0
  


