application:
  title: Wonder
  version: 1.0.0
  keycloak-url: ${KEYCLOAK_URL:https://keycloak-of5r5e4d7a-lm.a.run.app}
  realm: wonder
  client-id: wonder
  username: ${KEYCLOAK_ADMIN}
  password: ${KEYCLOAK_ADMIN_PASSWORD}
  mode: ${APP_MODE:DEV}
  admin-keycloak-id: ${ADMIN_KEYCLOAK_ID:9e3c01e8-795c-4c85-8af2-91b8b1c481ba}
  file-api:
    name: file-api
    url: ${FILE_API_URL:https://wonderfilemanagerepository-of5r5e4d7a-el.a.run.app}
  kaspi-api:
    url: ${KASPI_API_URL:https://kaspi.kz/shop/api/v2}
spring:
  codec:
    max-in-memory-size: 500KB
  datasource:
    url: ${DATABASE_URL}
    #    url: jdbc:postgresql://${DATABASE_DOMAIN:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:wonder}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER:${application.keycloak-url}/realms/${application.realm}}
          jwk-set-uri: ${OAUTH2_JWK:${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
server:
  servlet:
    context-path: '/api/'
  error:
    include-message: always
  port: ${PORT:8080}
  address: 0.0.0.0
  


