application:
  title: Wonder
  version: 1.0.0
  keycloak-url: ${KEYCLOAK_URL:http://34.118.60.220}
  realm: wonder
  client-id: wonder
  username: admin@mail.ru
  password: admin_password
  mode: ${APP_MODE}
  admin-keycloak-id: ${ADMIN_KEYCLOAK_ID:99d66d43-e8a1-4fe6-a854-8ce686c73ed6}
  file-api:
    name: file-api
    url: ${FILE_API_URL:https://file-manager-of5r5e4d7a-lm.a.run.app}
  kaspi-api:
    url: ${KASPI_API_URL:https://kaspi.kz/shop/api/v2}
spring:
  codec:
    max-in-memory-size: 500KB
  datasource:
    url: jdbc:postgresql://${DATABASE_DOMAIN}:${DATABASE_PORT}/${DATABASE_NAME}
    #    url: jdbc:postgresql://${DATABASE_DOMAIN:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:wonder}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: false
  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OAUTH2_ISSUER:${application.keycloak-url}/realms/${application.realm}}
          jwk-set-uri: ${OAUTH2_JWK:${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs}
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
server:
  servlet:
    context-path: '/api/'
  error:
    include-message: always
  port: ${PORT:8080}
  address: 0.0.0.0
  


