package kz.wonder.wonderuserrepository.dto.enums;

public enum OrderAvailableAction {
    START_ASSEMBLE, ASSEMBLE_PRODUCT, FINISH_ASSEMBLE,
    START_PACKING, PACK_PRODUCT, FINISH_PACKING,
    HANDLE_TO_CLIENT, HANDLE_TO_COURIER, HANDLE_TO_COURIER_EXPRESS, HANDLE_TO_ZAMMLER, HANDLE,NOTHING
}