name: Protect application.yml

on:
  pull_request:
    branches:
      - sensei
    paths:
      - 'path/to/your/application.yml'

jobs:
  check-author:
    runs-on: ubuntu-latest
    steps:
      - name: Reject changes if not authorized
        run: |
          if [ "${{ github.actor }}" != "Dulatbay" ]; then
            echo "You are not authorized to modify application.yml."
            exit 1
          fi
