name: Deploy to Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VM
      run: |
        ssh -o StrictHostKeyChecking=no grozergeorge80@34.125.159.241 << EOF
          cd WonderUserRepository
          git stash push -m "Saving my local changes"
          git pull --rebase origin main
          cp ~/wonder/Dockerfile .
          cp ~/wonder/docker-compose.yml .
          cp ~/wonder/application.yml ~/WonderUserRepository/src/main/resources/
          docker-compose up --build -d springapp
        EOF
